### ISSUE TITLE
ERROR: Execution of script 'Automatic URL Decoder' failed! URI malformed

### ISSUE THREAD

**Issue by Akilak11** [t1ml3arn-userscript-js/Automatic-URL-Decoder#1]
Привет, не буду много разглагольствовать. В тампер манки (хром).
http://prntscr.com/l673ou
а там сам смотри, что и как исправлять ;).

Да, еще линтер ругается на кавычки типо "{" - не везде расставляешь.
http://prntscr.com/l674ki
типо после IF ( ) - должны стоять кавычки {}, Некоторые пользователи, особенно перешедшие с питона, думают, что отступов достаточно.
Интерпретатор иногда правильно понимает, а иногда не знает, какую часть функции после If ( ) нужно отработать. И иногда может захватить слишком много или слишком мало ;).
спасибо за исправления ;).
Да и просьба обновить скрипт на гризифорк ;).

**Comment by T1mL3arn** [comment]
>http://prntscr.com/l673ou

Нужно больше информации. Ссылка на страницу, где происходит ошибка помогла бы.

>просьба обновить скрипт на гризифорк

Обновляется автоматически после изменений на гитхабе.

**Comment by Akilak11** [comment]
не обновляется вроде бы ;).16.10.2018, 14:07, "Timur" <notifications@github.com>:
http://prntscr.com/l673ou

Нужно больше информации. Ссылка на страницу, где происходит ошибка помогла бы.

просьба обновить скрипт на гризифорк

Обновляется автоматически после изменений на гитхабе.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Best regards Andrii Smykodub.-- +380507108658Skype ID: Akilak11 С уваженим Смыкодуб Андрей.+380507108658Skype ID: Akilak11

**Comment by T1mL3arn** [comment]
Ошибка `URI malformed` исправленна.
